### ISSUE TITLE
Ability to get a copy of a Array 2D

### ISSUE THREAD

**Issue by juzdepeche** [Eldoir/Array2DEditor#11]
Could it be possible for you to add the possibility to `Clone()` an array?

Here is my use case:

I have a Scriptable Object with an Array2DBool. I added some extension methods to your package suck as Matrix Transposition & Matrix Reflection. However, I use these transformation methods at runtime and I would like to only update a copy of my instance of Array2DBool but right now it also updates my scriptable object which I don't want to.

Thank you for this cool tool!

**Comment by jmsancho** [comment]
Same here, I've been looking for ways to make a deep copy; right now, only way I could get to work was to create a method which creates a regular 2D array (e.g. int[,] newArray) as an intermediate clone by iterating the entire Array2D, and then you can use that array to set any instances of array2D with the cloned values.

There's probably a better implementation for this?

**Comment by Eldoir** [comment]
Hello, thanks for your comments :) I will look into it. It'll probably end up in having to implement some interface on the Array2D's to make it clonable. I will implement for the basic Array2Ds that exist in the plugin, and if you have arrays of custom types, you'll probably just have to implement this interface on your custom type to be able to copy an entire array.
I'm thinking of the System.ICloneable interface to stay the more generic possible ([MSDN](https://docs.microsoft.com/fr-fr/dotnet/api/system.icloneable.clone?view=net-6.0)).
What do you think?

Edit: BTW @jmsancho I'm not sure about what you think a deep copy is. To me, a deep copy is when you have to copy fields of a reference type. (e.g. you have a "MyClass" method that contains multiple fields). If you simply want to clone an array of int's, then it is a shallow copy because int is a value type. Feel free to correct me if I'm wrong!

**Comment by jmsancho** [comment]
I am not well versed enough to recommend a proper implementation path I think :) but it sounds about right?

and about shallow vs. deep copy, I was under the impression that a shallow copy of the array A would be creating another array B which is actually referencing the same elements in memory (i.e. modifying an element of array B would also modify the same element of array A as they are referencing the same place in memory); a deep copy would create a new array B where each element has the same value as A initially, but each element is actually on a new spot in memory, so modifying one does not affect the other.

I might be way off tho

**Comment by Eldoir** [comment]
Hello, I apologize for the delay!
I've been working on it for a few hours today, I hope you will find it easy to use.
It's now available on `master`.
Basically I've added an implementation for `ICloneable` on Array2D, so all you have to do on any Array2D<T> is to call the Clone() method to get a fresh copy.
If your Array2D is an array of reference types (complex objects of yours), it simply must implement ICloneable.
It then should work without a hitch.

Please note that for your current code to support this update, your custom Array2D's will have to implement the following method:
`Array2D<T> Clone(CellRow<T>[] cells)`
You can have a look at the existing implementations for the base types to see an example, like for ints:
```csharp
protected override Array2D<int> Clone(CellRow<int>[] cells)
{
    return new Array2DInt() { cells = cells.Select(r => new CellRowInt(r)).ToArray() };
}
```
It should just be a matter of copy/pasting this code and changing the types to yours.

Also, your custom `CellRow<T>` classes will now have to have a default parameterless constructor, and a copy constructor that takes their base class as an argument, like this (still for ints):
```csharp
[System.Serializable]
public class CellRowInt : CellRow<int>
{
    /// <inheritdoc/>
    [UsedImplicitly]
    public CellRowInt() { }

    /// <inheritdoc/>
    public CellRowInt(CellRow<int> row)
        : base(row) { }
}
```
Again, nothing complicated, you should just have to copy/paste this and change the types.
The `[UsedImplicitly]` is just here for R# users, I know there are a lot of them out there, and I think it better reflects the intent since there is no direct usage of the constructor in the code.
Also, the `inheritdoc` makes it more user-friendly when hovering the method, without having to copy/paste the summary from the base class. Again, not mandatory, but nice-to-have.

Please let me know if you have any question or feedback, I've made sure it worked on my use cases but yours could be more complex and I cannot foresee every situation 😃 Cheers!
