### ISSUE TITLE
GridSize X,Y reverse?

### ISSUE THREAD

**Issue by SyaoranChang** [Eldoir/Array2DEditor#4]
Hi,

I set Example_Bool Grid size X:9 Y:11
But cells is cells[11,9]

ExampleScript.cs line 30 will crash when X:0 Y:9

![Snipaste_2020-10-06_18-36-17](https://user-images.githubusercontent.com/18550228/95191501-71acb480-0803-11eb-9192-8e3c97e74afb.png)
![Snipaste_2020-10-06_18-37-03](https://user-images.githubusercontent.com/18550228/95191508-73767800-0803-11eb-830a-e1b2d906b2e4.png)

**Comment by Eldoir** [comment]
Wow, thanks for the catch!
Sorry for not replying sooner, I hadn't been notified.

This is now fixed (as well as update to `2019.4.13f1 LTS`).

Please note that _**X**_ now means _**ROWS**_, while _**Y**_ now means _**COLUMNS**_.

It makes more sense to me in the code, as I'm used to these as a programmer, and I assume most people using this plugin are programmers because you can't really do anything with the data without some code.

Thanks again for using `Array2DEditor`. It helps me evolving as a professional programmer!
