### ISSUE TITLE
2 lines blocking from use in .NET 3.5 

### ISSUE THREAD

**Issue by OlGimpy** [Eldoir/Array2DEditor#6]
Stuck on an old version of .NET and Unity is throwing an error for two lines in Array2D.cs -- I'm not super great with code (artist brain!), so I don't know how to rewrite these in a 3.5 friendly way. Is this something you could help me with?

`17 public Vector2Int GridSize => gridSize;`

and 

`45 public T this[int i] => row[i];`

Thank you!

**Comment by OlGimpy** [comment]
Fixed! I replaced all the of 

`=>`

with 
```
{ 
get { return #; } 
}
```
throughout the package

**Comment by Eldoir** [comment]
Hi, first of all, thanks for your comment and sorry for the issue!
I should've expected that someday, someone would have a compatibility issue with this new syntax...
This is from C# 7.0 and for the record, that feature is called [expression-bodied member](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/expression-bodied-members).
From Unity's website, it seems the first version that supports C# > 7.0 is [2018.3](https://unity3d.com/unity/whats-new/unity-2018.3.0).

So, I assume you have a Unity version < 2018.3: if that is the case, and you are able to upgrade to the latest 2018 LTS version of Unity ([2018.4.32](https://unity3d.com/unity/whats-new/2018.4.32)), this will probably not break your project and you will be able to support the new syntax.

Otherwise, you did very well by changing this `=>` syntax to good ol' `{ get { return ; } }`.
This is exactly what I would've done to get you up and running.

Kudos to you and thanks for using **Array2DEditor**!
Any suggestion/improvement/issue submitted is welcome! :)

**Comment by OlGimpy** [comment]
Thank you!! We're on 2018.4.1f, and that issue's been driving me nuts but we're a little stuck as far as versions go. I'll try the next step up and see if it helps.

I have a weird question regarding the Editor files though, is it possible to have 3 different arrays in the same ScriptableObject? I'm trying to replace our random LabyrinthAlgorithm with premade ScriptableObject blueprint assets for level layouts, and would like to have 3 tethered arrays (Floorplan, Door nodes, Decor nodes) that can all be edited from the same file. 

Something like this:
[https://imgur.com/Qq9PfwN](https://imgur.com/Qq9PfwN)

I've been trying to get just two in one file to start, but am starting to think there might be some reason I'm unaware of that this isn't possible? Or should I be able to do this?

Edit: bird's eye of a generated level in-game: [https://imgur.com/vKaOOdA](https://imgur.com/vKaOOdA)

**Comment by Eldoir** [comment]
That's actually not a weird question at all, and something that would be much more convenient to work with I guess.
In programming, we more often ask how much time will be needed to do this, not if that's possible :>
I'll try to make it possible, I have a few ideas in mind to try to achieve what you want.
I'll keep you posted as I progress! Meanwhile, good luck with your game :) Interesting look!

**Comment by OlGimpy** [comment]
Oh dude, that's amazing. If you have an idea for how it can be done... I was just going to fumble around copy and pasting more. Thank you so much! Do you have a tip jar somewhere?

**Comment by Eldoir** [comment]
Hello again,
I've made some progress during the weekend.
I still have a weird bug in build where the app is crashing at execution for an odd reason.
I also need to figure out some other details about serialization, but so far, here's how it looks:
![image](https://user-images.githubusercontent.com/30863193/108719087-727a8480-751f-11eb-9a5b-5c9a088dc414.png)
You can also directly use the arrays in a script, you're not limited to ScriptableObjects anymore:
![image](https://user-images.githubusercontent.com/30863193/108719241-9a69e800-751f-11eb-8c83-29d1c84e25ef.png)
This smells good but I'm still missing the key feature :) I'll come back when I have more!
And no I don't have any tip jar but I'm glad you're using Array2DEditor, that's it ^^

**Comment by OlGimpy** [comment]
This is great! Exactly what I had been trying to do. It also seems like being able to repurpose individual arrays into a script could be a huge plus for anyone using this package, especially for one-off type scripts. Thank you so much for making this!

**Comment by Eldoir** [comment]
Hey!
The plugin is ready! You can pull from the master branch :) Hope you'll like it!
Please note that it currently doesn't display very well with arrays of Array2D's, but I don't think you'll need it really soon. I'll try to fix it in the meantime.
Also, I had a hard time figuring how I could work together with the Unity version the plugin is currently in (2019.4.13) and your version, which needs an older C# syntax.
I ended up keeping the Unity version of the plugin, since it doesn't feel right to take a step back.
So, I guess you'll have to do the => { get { return #; } } replacement again... sorry for this!
Have you been able to upgrade your version of Unity since?
If you have any other suggestion, feel free! :) And thanks again for using the plugin, it's really great to see that it's useful to people!

**Comment by OlGimpy** [comment]
Incredible. I will be implementing this as best I can this evening/weekend and will let you know how it goes! No worries at all about the syntax, just the price of working in one project for so many years D:
