### ISSUE TITLE
Change grid size shows fully empty window

### ISSUE THREAD

**Issue by AlexanderPopov86** [Eldoir/Array2DEditor#7]
Unity 2021.1.7f1 professional
Selecting "Change Grid Size" or cell size always shows an empty window. No fields like it's on gif on "code" tab here. No errors or warnings in console of unity.

After playing around with it a little bit in EditorWindowVector2IntField class on line 29 if I swap it from
window.ShowModalUtility();
to
window.ShowPopup();
that window becomes visible properly and fully operational.

**Comment by Eldoir** [comment]
Hello, thanks for using Array2DEditor! 😄  It means a lot to me!
And thanks for your detailed bug report and your Unity version.
I'm gonna investigate this asap and provide a proper fix that will fit both old and new versions of Unity.
There must be something with a change in the API after upgrading to Unity 2021 or something like that.

**Comment by Eldoir** [comment]
Hello again,
Thanks for the fix you proposed.
I decided to use `window.ShowPopup()` as you proposed, because it's no big deal if the window is not a modal one after all.
At least it seems to fix it for all Unity versions.
It is worth mentioning that I first tried to repro with Unity 2021.1.13f1 (the most recent one as of today), and I couldn't repro, so something must've happened in Unity API that fixed it between 2021.1.7 and 2021.1.13. Better safe than sorry still 😃
I'm closing this and feel free to come back if you have another issue/suggestion!
